name = "zk-auto-clock-in"
main = "worker.js"
compatibility_date = "2023-12-01"

# 添加定时触发器配置
[triggers]
crons = ["2 16 * * *"]  # 每天UTC时间16:02触发（对应北京时间凌晨00:02）

[vars]
# 日志控制设置
ENABLE_LOGGING = "false"  # 设置为 "true" 启用日志输出，设置为 "false" 禁用日志输出

# 打卡内容设置
SPORTS_COMMENT = "来自必应的精美壁纸！"  # 运动打卡内容，默认为"来自必应的精美壁纸！"
DAILY_COMMENT = "今日学习内容总结，收获满满！"  # 日精进打卡内容，默认为"今日学习内容总结，收获满满！"

# 登录信息设置，自行修改
ZU_XIA_USERNAME = "530XXXXXXXXXXXXXXX" # 用户名
ZU_XIA_PASSWORD = "0XXXXX" # 密码

# 本地开发配置
[env.development]
name = "zuxia-login-dev"